language: php
os:
  - linux
  - windows
version: ~> 1.0
php: "7.3"

cache:
  directories:
    - "$HOME/.composer/cache"

services:
  - mysql

env:
  global: ADS_PRINT_COMMAND_OUTPUT=1

# @see https://pantheon.io/blog/highest-lowest-testing-multiple-symfony-versions
jobs:
  include:
    - php: 7.4
      env: 'HIGHEST_LOWEST="update"'
    - php: 7.3
      env: 'HIGHEST_LOWEST="update --prefer-lowest"'

before_install:
  - composer selfupdate

install:
  # Load composer dependencies.
  - composer validate --no-check-all --ansi
  - 'composer -n ${HIGHEST_LOWEST-install} --prefer-dist -o'
  - ./bin/ads auth:login --key=notarealkeyatall --secret=thisisaplaceholder

script:
  - composer test

after_success:
  - ./vendor/bin/php-coveralls -vvv
